version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      # Add static files for nginx to serve.
      - ./website/static:/website/static
    depends_on:
      - django
    networks:
      - django_frontend-net
    ports:
      - 8000:80
  django:
    image: dtempleton/django:latest
    depends_on:
      - db
    env_file:
      - ./env/django-mariadb.env
      - ./env/django.env
      - ./env/dev.env
    volumes:
      - ./website:/home/django/website
    networks:
      - django_frontend-net
      - django_backend-net
  db:
    image: mariadb:latest
    networks:
      - django_backend-net
    env_file:
      - ./env/django-mariadb.env
      - ./env/mariadb.env
    volumes:
      - ./db/mysql:/var/lib/mysql

networks:
  django_frontend-net:
    name: django_backend-net
  django_backend-net:
    name: django_backend-net
