version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - django
    networks:
      - django_frontend-net
    ports:
      - 8000:80
  django:
    image: dtempleton/django:latest
    depends_on:
      - db
    env_file:
      - ./env/django-mariadb.env
      - ./env/django.env
      - ./env/dev.env
    networks:
      - django_frontend-net
      - django_backend-net
  db:
    image: mariadb:latest
    networks:
      - django_backend-net
    env_file:
      - ./env/django-mariadb.env
      - ./env/mariadb.env
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/dump:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/my.cnf
      - ./db/conf.d:/etc/mysql/conf.d

networks:
  django_frontend-net:
    name: django_backend-net
  django_backend-net:
    name: django_backend-net
